stages:
  ingest:
    cmd: py -m src.data.ingest
    deps:
      - src/data/ingest.py
      - ../shared/data/raw/pc-parts-json
      - src/data/parts_attrs_dict.py
      - src/data/parse_utils.py
    outs:
      - ../shared/data/interim/pc-parts-merged.csv
  preprocess:
    cmd: py -m src.features.preprocess
    deps:
      - ../shared/data/interim/pc-parts-merged.csv
      - src/features/preprocess.py
      - src/utils/tokenization.py
    outs:
      - ../shared/data/processed/pc-parts-processed.csv